# permissions for end users to view azdevopsagentpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azdevopsagentpool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: azdevops-operator
    app.kubernetes.io/part-of: azdevops-operator
    app.kubernetes.io/managed-by: kustomize
  name: azdevopsagentpool-viewer-role
rules:
- apiGroups:
  - vortal.biz
  resources:
  - azdevopsagentpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vortal.biz
  resources:
  - azdevopsagentpools/status
  verbs:
  - get
