---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vortal.biz
  resources:
  - azdevopsagentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vortal.biz
  resources:
  - azdevopsagentpools/finalizers
  verbs:
  - update
- apiGroups:
  - vortal.biz
  resources:
  - azdevopsagentpools/status
  verbs:
  - get
  - patch
  - update
